"
" ENVIRONMENT
"
if !has('nvim') && !empty($XDG_CONFIG_HOME)
    "shift as much vim cruft out of $HOME
    set directory=$XDG_CACHE_HOME/vim,/tmp
    set backupdir=$XDG_CACHE_HOME/vim,/tmp
    set viminfo+=n$XDG_CACHE_HOME/vim/viminfo,'33
    set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIMRUNTIME
endif
if !empty($XDG_DATA_HOME)
    "work out of XDG_DATA_HOME, if possible
    let g:python2_host_prog = expand("$XDG_DATA_HOME/vim/venv2/bin/python2")
    let g:python3_host_prog = expand("$XDG_DATA_HOME/vim/venv3/bin/python")
    let g:plug_home = expand("$XDG_DATA_HOME/vim/plugged")
endif

"
" PLUGINS
"
call plug#begin()
Plug 'airblade/vim-gitgutter'           "track file changes
Plug 'justinmk/vim-dirvish'             "slick wrapper on netrw
Plug 'justinmk/vim-sneak'               "lightweight easymotion
Plug 'ludovicchabant/vim-gutentags'     "ctags/cscope manager
Plug 'romainl/vim-qf'                   "quickfix window enhancements
Plug 'romainl/vim-qlist'                "use quickfix as much as possible
Plug 'tommcdo/vim-lion'                 "align text by char with 'gl', 'gL'
Plug 'tpope/vim-abolish'                "useful in way nobody can describe
Plug 'tpope/vim-characterize'           "more useful 'ga'
Plug 'tpope/vim-commentary'             "quick comment/uncomment
Plug 'tpope/vim-eunuch'                 "vim sugar on common unix commands
Plug 'tpope/vim-fugitive'               "vim sugar on some git commands
Plug 'tpope/vim-repeat'                 "extends default 'repeat action'
Plug 'tpope/vim-rsi'                    "love me some emacs keybindings
Plug 'tpope/vim-surround'               "adds an 's' (surround) operator
Plug 'tpope/vim-unimpaired'             "great set of complimentary remaps
Plug 'w0rp/ale'                         "async linting
Plug 'wellle/targets.vim'               "beautifully extends default textobj

Plug 'octol/vim-cpp-enhanced-highlight' "tried to live without this, couldn't
Plug 'reedes/vim-lexical'               "keymaps, sensible spellcheck
Plug 'reedes/vim-litecorrect'           "lightweight autocorrect

Plug 'tpope/vim-obsession'              "TODO: use more or delete
Plug 'tpope/vim-projectionist'          "TODO: use more or delete
Plug 'kana/vim-textobj-user'            "depend for lots of textobjs

Plug 'lyuts/vim-rtags'                  "needs an rdm socket
Plug 'fatih/vim-go'                     "not a gopher
Plug 'HerringtonDarkholme/yats.vim'     "not a js dev

"Plug 'morhetz/gruvbox'
"let g:gruvbox_termcolors=16         "work in any emulator with no fuss
"let g:gruvbox_contrast_dark='low'   "gruvbox can be a bit sharp sometimes
"let g:gruvbox_invert_selection=0    "nicer-looking visual mode selections

Plug 'lifepillar/vim-solarized8'     "solarized, some bullshit

"mostly for definition/keybindings
Plug 'davidhalter/jedi-vim', { 'for': 'python'}
"objs -- f:function, c:class
Plug 'bps/vim-textobj-python', { 'for': 'python' }

"NeoVim only: async autocomplete
Plug 'Shougo/deoplete.nvim', !has('nvim') ? { 'on': [], 'for': [] } : {}
Plug 'zchee/deoplete-jedi', !has('nvim') ? { 'on': [], 'for': [] } : {}

"NeoVim/Vim8 only: async Unite.vim
Plug 'Shougo/denite.nvim', !has('nvim') ? { 'on': [], 'for': [] } : {}

"only-for-some-filetype jail (this is probably a tad obsessive)
Plug 'junegunn/goyo.vim', { 'for': 'markdown' }
Plug 'junegunn/limelight.vim', { 'for': 'markdown' }
Plug 'mphe/grayout.vim', { 'for': ['c', 'cpp'] }
Plug 'reedes/vim-pencil', { 'for': 'markdown' }
Plug 'reedes/vim-textobj-sentence', { 'for': 'markdown' }
call plug#end()

"
" GENERAL SETTINGS
"
filetype plugin indent on
syntax enable

runtime macros/matchit.vim

set noerrorbells                "don't beep the terminal incessantly
set novisualbell                "don't set the visual bell incessantly
set t_vb=                       "yet another place we need to disable bells

set autoindent                  "minimal auto-indent for any filetype
set backspace=indent,eol,start  "proper backspace behaviour
set formatoptions+=j,1          "prune comments on joins, smarter linebreak
set hidden                      "allow more than one unsaved buffer
set cindent                     "saner indent logic
set smarttab                    "backspace tries to delete shifwidth/tabstop
set list                        "show trailing whitespace,tabs
set tags=./tags;,tags           "look for tags in current dir, parent dirs
set virtualedit=block           "cursor goes (almost) anywhere in visual mode

set switchbuf=useopen,usetab    "try and find prexisting buffers

set wildmenu                    "comand-line completion
set wildignorecase              "ignore casei n wildmenu completion
set wildignore+=*.swp,*.bak     "clean up the wildmenu
set wildignore+=*/.git/**/*,*/.hg/**/*,*/.svn/**/*
set wildignore+=*/min/*,*/vendor/*
set wildignore+=*.tar.*,*.pyc
set wildignore+=tags,cscope.*

set path=.,**                   "search current directory, all subdirectories
set history=100                 "small command history
set formatoptions+=1            "don't break on 1-letter words

set complete-=i                 "don't scan current/included files
set nrformats-=octal            "don't show octal with ga (vim-characterize)
set title titlestring=%F        "show the filepath as the title

set ttimeout                    "wait for keycodes to complete
set ttimeoutlen=100             "timeout for keycodes

set autoread                    "reload changed files when possible
set sessionoptions-=options     "don't save options in sessions
set noswapfile                  "never saw the point of .swp

set number                      "line numbers
set expandtab                   "spaces > tabs, whenever possible
set shiftwidth=4                "4 spaces per indent level
set tabstop=4                   "tab = 4 spaces (mostly for Makefiles)
set shiftround                  "round indent to multiples of 4

set splitbelow                  "open new hsplits to the bottom
set splitright                  "open new vsplits to the right
set previewheight=1             "smaller preview window

set gdefault                    "/g enabled in substitute command by default
set ignorecase                  "ignore case when matching patterns by default
set smartcase                   "override ignorecase if pattern has capitals

set colorcolumn=79              "don't go crazy with tabs
set breakindent                 "wrapped lines inherit indent
set nowrap                      "explicitly wrap with :wrap
set scrolloff=5                 "small offset at the screen right
set scrolloff=8                 "small offset at the screen bottom

set foldlevelstart=99           "don't collapse anything by default
set foldmethod=indent           "use indent to form folds

set mouse=                      "disable mouse
"set cscopetag                  "use cscope tags in addition to ctags
"set csto=1                     "search ctags before cscope

set incsearch                   "show matches while searching
if maparg('<C-L>', 'n') ==# ''  "<C-L> to clear incsearch hl
    nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
endif

"aggressively open folds automatically
set foldopen=hor,insert,jump,mark,percent,quickfix,search,tag,undo
"show trailing whitespace + tabs with ':set list'
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·
"always use a popup complete menu, insert longest common text, preview window
set completeopt=menu,menuone,longest,preview

"
" THEMING
"
set background=dark
let g:solarized_term_italics = 0
let g:solarized_statusline = 'low'
let g:solarized_visibility = 'low'
let g:solarized_diffmod = 'low'
colorscheme solarized8_dark_high

"
" GUI
"
set guifont=Hasklig:h13

"
" PERFORMANCE TWEAKS
"
set lazyredraw                  "no screen redraw during macros
aug use_ag                      "ag is faster than grep, use if installed
    if executable('ag')
        set grepprg=ag\ --vimgrep\ $*
        set grepformat=%f:%l:%c:%m
    endif
aug END

"
" STATUSLINE
"
set laststatus=2                            "always show the status bar
set statusline=                             "rhs statusline
set stl+=\ %t%m\                            "relative file path
set stl+=%(\ %{fugitive#head(1)}%)\        "current git branch
set statusline+=%=                          "lhs statusline
set stl+=%(%{&filetype}\ \|\ %)             "filetype
set stl+=%([%W%R]\ %)                       "flags
set stl+=%(%3l/%L☰\ :%2v\ %)                "cursor/line position, %'age

"
" KEYMAPS
"
let mapleader="\<Space>"                    "sensible mapleader

"
" AUTOCOMPLETE SETTINGS
"   Use Deoplete.nvim if running under the right environment
"
if has('nvim') && has('python3')
    let g:deoplete#enable_at_startup=1      "start deoplete at launch

    "trigger completions with <C-Space>
    let g:deoplete#disable_auto_complete=1
    inoremap <expr><C-Space> deoplete#manual_complete()
    inoremap <expr><C-@> deoplete#manual_complete()

    "python competion via deoplete-jedi, not jedi-vim
    let g:jedi#completions_enabled=1
    let g:jedi#force_py_version=3
    let deoplete#sources#jedi#show_docstring=1
endif


"
" PLUGIN SETTINGS
"
let g:gitgutter_map_keys=1              "use the gitgutter keybinds
let g:grayout_confirm=0                 "autoload grayout.vim config files
let g:sneak#streak=1                    "vim-sneak smart streak mode

"try and match <file>.{cpp,h} together in cpp projects
let g:projectionist_heuristics = {
      \   "cpp/": {
      \     "*.cpp": {
      \        "alternate": "{}.h",
      \     },
      \     "*.h": {
      \        "alternate": "{}.cpp",
      \     },
      \   },
      \ }

"
" CUSTOM FUNCTIONS
"
function! StripWhitespace()
  if !&binary && &filetype != 'diff'
    normal mz
    normal Hmy
    %s/\s\+$//e
    normal 'yz<CR>
    normal `z
  endif
endfunction
command! StripWhitespace :call StripWhitespace()
