#!/usr/bin/env bash

# dotfile arrays to be linked into the user's home dir
export dotfiles=(
    'all' 'home/.gitconfig' 	         ''
    'deb' 'home/.i3'	            	 ''
    'osx' 'home/.tmux.conf' 	         ''
    'all' 'home/.vim'       	         ''
    'all' 'home/.vim' 		             '.config/nvim'
    'all' 'home/.vim/init.vim'	         '.vimrc'
    'all' 'home/.zsh'                    ''
    'all' 'home/.zshenv'  	             ''
    'all' 'home/.zprezto' 	             ''
    'all' 'home/.zpreztorc'          	 ''
    'all' 'home/.zprofile'  	         ''
    'all' 'home/.zshrc'     	         ''
    'all' 'home/.zsh/prompt/minimal.zsh'      '.zfunctions/prompt_minimal_setup'
    'all' 'home/.zsh/prompt/pure/pure.zsh'    '.zfunctions/prompt_pure_setup'
    'all' 'home/.zsh/prompt/pure/async.zsh'   '.zfunctions/async'
)
