#!/usr/bin/env bash

# assume we're sitting in the conf.d directory
if [[ -z "$1" ]]; then 
	SYMLINK_FILE=${HOME}/.dotfiles/res/symlinks
else
	SYMLINK_FILE=${1}
fi
source $SYMLINK_FILE

if [[ -z "$dotfiles" ]]; then echo "No dotfiles given to link"; fi

# link dotfiles as defined in the dotfile array
for (( i=0; i < ${#dotfiles[@]}; (i+=3) )); do
    plat=${dotfiles[$i]}
    src=${HOME}/.dotfiles/${dotfiles[$((i+1))]}

    tgt=${dotfiles[$((i+2))]}
    [[ ${tgt:0:1} != "/" ]] && tgt="$HOME/$tgt"
        
    # check for platform-specific elements
    if [[ "$plat" != "all" ]]; then 
        [[ -n "$HAS_OSX" && "$plat" != "osx" ]] && continue
        [[ -n "$HAS_DEB" && "$plat" != "deb" ]] && continue
    fi

    # make sure the parent dir exists
    if ! [[ -d "$(dirname \"$tgt\")" ]]; then
        mkdir -p $(dirname "$tgt")
    fi

    # link the file
    ln -svnf ${src} "${tgt}"
done    

