# figure out exaclty where we're running on
if [[ $(uname) == 'Darwin' ]]; then
  has_osx=1
else
  has_linux=1
fi

# prezto setup 
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [ -n "$has_osx" ]; then
  export PATH=/opt/local/bin:/opt/local/sbin:$PATH
  alias vi='nvim'
else
  alias vi='NVIM_TUI_ENABLE_TRUE_COLOR=1 nvim'
fi

# general opts
bindkey -e
setopt autocd correct extendedglob histignorealldups nomatch notify sharehistory
