# figure out exaclty where we're running on
if [[ $(uname) == 'Darwin' ]]; then
  has_osx=1
else
  has_linux=1
fi

# prezto setup 
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [ -n "$has_osx" ]; then
  export PATH=/opt/local/bin:/opt/local/sbin:$PATH
fi

# general opts
bindkey -e
setopt autocd correct extendedglob histignorealldups nomatch notify sharehistory

# aliases
alias vi='nvim'

# Base16 Shell Theme
BASE16_SHELL="$HOME/.dotfiles/theme/base16-shell/base16-eighties.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
